apiVersion: v1
kind: Service
metadata:
  name: hiring-app-service
spec:
  selector:
    app: hiring-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080 # You can choose an available port in the NodePort range (30000-32767)
